### ISSUE TITLE
Some optimizations

### ISSUE THREAD

**Issue by minecrawler** [Charliekenney23/query-str#1]
Just some ideas for your project. They might be over-kill for this small package, however can prepare you for bigger projects

- Set up [travis-ci](https://travis-ci.org/) or similar to make sure that your project is always building
- Add code coverage (for example using [coveralls](https://coveralls.io/)) to make sure that you actually test all branches
- Set up linting (your lint file is empty atm). You might want to give the [airbnb](https://github.com/airbnb/javascript) rules a try
- Set up [GitFlow](http://nvie.com/posts/a-successful-git-branching-model/)
- Clean your package.json (is that dependency really needed? Shouldn't it be a dev-dep?)
- Set up [greenkeeper](https://greenkeeper.io/)
- Set up [snyk](https://snyk.io/)
- Add [JSDoc](http://usejsdoc.org/) comments in your code so new developers easily know their way around the code (well, here it is not necessary, just think of bigger projects)

Of course, you do not need all those services all the time, however since you wrote that you want to practice, my list might give you a little insight into what kind of tools there are available.

The code itself looks good imho. It just has to work and everything is good :)

Additional homework: summarize what each of the above mentioned tools is used for and why it does (or does not) make sense to use it :)

Regards,

Marco from HN

**Comment by 0xch4z** [comment]
@minecrawler  I think I've satisfied all of the necessary points so I'm going to close this. Thanks for the suggestions!
